### ISSUE TITLE
.git-acc:259: command not found: complete

### ISSUE THREAD

**Issue by TheErondu** [tw-yshuang/Git_SSH-Account_Switch#11]
I just installed this script on my MacBook Pro running on Ventura 13.5.2.
every time i load my terminal i get 
`.git-acc:259: command not found: complete`

what could be the cause?

**Comment by tw-yshuang** [comment]
Is your shell using `zsh`?

**Comment by TheErondu** [comment]
yes... zsh

**Comment by tw-yshuang** [comment]
That's weird. I am also using MBP, maybe you can try to reinstall it and see what happens.

**Comment by longnguyen2508** [comment]
> source ~/.zshrc

Resolved this issue

**Comment by tw-yshuang** [comment]
Thanks!

**Comment by TheErondu** [comment]
didn't solve it for me... are you on ventura 13.6?

what exactly does 
`complete -F _git-acc git-acc` do? i commented it out and the error is gone.
